import LocalizedStrings from "react-native-localization";

export const Strings = new LocalizedStrings({
    "en-US": {
        welcome_to: "Welcome to",
        my_bsw_health: "MyBSWHealth",
        sign_in: "Sign In",
        register: "Register",
        find_a_doctor: "Find a Doctor",
        welcome: "Welcome",
        appointment: "Appointment",
        new: "New",
        see_all: "See All",
        messages: "Messages",
        save_username: "Save Username",
        forgot: "Forgot",
        username: "Username",
        or: "or",
        password: "Password?",
        register: "Register",
        finda_a_doctor: "Find a Doctor",
        find_a_location: "Find a Location",
        find_doctors_in_your_network_see: "Find doctors in your network, see",
        their_detailed_profiles_and_seemlessly: "their detailed profiles, and seemlessly",
        schedule_appointments: "schedule appointments.",
        search_for_clinics_doctors_offices: "Search for clinics, doctor's offices,",
        emergency_medical_centers_walkin: "emergency medical centers, walk-in",
        clinics_and_more_near_you: "clinics and more near you.",
        if_this_is_an_emergency_please_contact_911: "If this is an emergency, please contact 911",
        schedule_an_appt: "Schedule an Appt",
        book_an_appointment_with_your: "Book an appointment with your",
        doctors_or_explore_options: "doctors or explore options.",
        get_care_online: "Get Care Online",
        get_care_without_going_into_the_doctors: "Get care without going into the doctors",
        office: "office.",
        find_care_or_get_help: "find care or get help",
        skip_the_doctors_office: "Skip the doctor's office",
        with_an_e_visit: "with an E-Visit",
        online: "Online",
        interview: "Interview",
        diagnosis_by: "Diagnosis by",
        a_clinician: "a Clinician",
        response: "Response &",
        prescription: "Prescription",
        if_needed_in_1hr: "(if needed) in 1hr",
        start_e_visit: "Start E-Visit",
        symptoms_we_treat: "symptoms we treat",
        cold_flu_allergies: "Cold,Flu,Allergies",
        skin_conditions: "Skin Conditions",
        tobacco_cessation: "Tobacco Cessation",
        stomach_and_digestive_issues: "Stomach and Digestive Issues",
        minor_eye_conditions: "Minor Eye Conditions",
        vaginal_yeast_infection: "Vaginal yeast infection",
        bladder_infection: "Bladder infection(UTI)",
        get_care_online: "Get Care Online",
        office_visit_with_a_doctor: "office visit with a doctor",
       



        //////////////////////////////////////////////////

        call_failed: "Call Failed",
        cannot_make_call: "Could not make a phone call on this device.",
        cannot_open_map: "Could not open map for this address.",
        day: "Day",
        days: "Days",
        error: "Error",
        ok: "OK",
        save_text: "Save",
        success: "Success",
        today: "Today",
        na: "N/A",
        account_change_password_heading: "Change Your Password",
        account_change_password_button_title: "Change Password",
        account_change_password_confirm_new_match: "Confirm and New Password must match",
        account_change_password_error_message: "There was an error changing your password.  Please check your entries and try again.",
        account_change_password_incorrect_password: "The Old Password you entered does not match. Please check your entry and try again.",
        account_change_password_successful: "Your password has been changed.",
        account_change_password_at_least_8: "At least 8 characters long",
        account_change_password_upper_case: "Upper Case Letter",
        account_change_password_lower_case: "Lower Case Letter",
        account_change_password_a_number: "A Number",
        account_change_password_special_char: "and/or Special Character",
        account_enter_first_name: "Enter First Name",
        account_enter_last_name: "Enter Last Name",
        account_enter_zip_code: "Enter Zip Code",
        account_enter_email: "Enter Email",
        account_enter_dob: "Enter Birth Date",
        account_enter_username: "Enter Username",
        account_enter_old_password: "Enter Old Password",
        account_enter_new_password: "Enter New Password",
        account_enter_confirm_password: "Confirm New Password",
        account_forgot_password_heading: "Use this form to retrieve/reset your password.",
        account_forgot_password_button_title: "Retrieve password",
        account_forgot_password_alert: "Please check your email for further instructions.",
        account_forgot_password_error_message: "Your password could not be reset using the information supplied. Please check your entries and try again.",
        account_forgot_username_heading: "Use this form to retrieve your username.",
        account_forgot_username_button_title: "Find username",
        account_forgot_username_error_message: "Your username could not be retrieved using the information supplied.  Please check your entries and try again.",
        account_forgot_username_success_message: "Your username of {0} has been copied to your clipboard.",
        account_go_to: "Go to account",
        appointments_book_appt: "Book an appointment with your doctors or explore other options.",
        appointments_echeckin_available: "eCheck-in Available",
        appointments_echeckin_completed: "eCheck-in Completed",
        appointments_get_care_online: "Get Care Online",
        appointments_get_care_without: "Get care without going into the doctor’s office via video or e-visit.",
        appointments_high_five: "High five! You’ve earned the gift of time.",
        appointments_no_upcoming: "You have no upcoming appointments.",
        appointments_save_time: "Save time at the office!",
        appointments_schedule_an_appt: "Schedule an Appt",
        appointments_title: "APPOINTMENTS",
        billing_balance_unavailable: "Balance not Available",
        billing_header: "BILLING",
        contact_us_support_center_title: "MyBSWHealth Support Center",
        contact_us_health_plan_title: "Scott & White Health Plan",
        contact_us_emergency_tile: "Medical Emergency",
        dashboard_error_message: "Failed to load. Please try again.",
        edit_contact_city: "City",
        edit_contact_email: "Email",
        edit_contact_mobile_phone: "Mobile Phone",
        edit_contact_state: "State",
        edit_contact_street_address_1: "Address Line 1",
        edit_contact_street_address_2: "Address Line 2",
        edit_contact_save_error: "There was a problem saving your contact information. Please try again later.",
        edit_contact_load_error: "There was an error loading this page. Please try again later.",
        edit_contact_zip_code: "Zip Code",
        edit_insurance_company: "Company",
        edit_insurance_group_id: "Group ID",
        edit_insurance_member_id: "Member ID",
        edit_insurance_phone_number: "Phone Number",
        edit_insurance_save_error: "There was a problem saving your insurance information. Please try again later.",
        edit_insurance_load_error: "There was an error loading this page. Please try again later.",
        healthcard_bswh_header: "SCOTT AND WHITE HEALTH PLAN",
        healthplan_card: "Card",
        healthplan_claims_title: "CLAIMS",
        healthplan_dash_title: "DASH",
        healthplan_details: "Details",
        healthplan_plan_title: "PLAN",
        healthplan_title: "Health Plan",
        healthplan_tier_title: "In-Network Only",
        healthplan_cant_connect: "Unable to load the Health Plan website. Please check your connection and try again.",
        insurance_card: "Insurance Card",
        insurance_card_failed_title: "Yikes!",
        insurance_card_failed_header: "Something went wrong.",
        insurance_card_failed_subheader: "Please try again.",
        insurance_card_auth_failed: "Your session has ended. Please log in again.",
        insurance_card_add_to_wallet: "Add to Apple Wallet",
        insurance_card_added_to_wallet_alert: "Pass Added",
        insurance_card_added_to_wallet: "The pass for your insurance card has been added to the wallet.",
        insurance_card_added_to_wallet_error_alert: "Error Adding Pass",
        insurance_card_added_to_wallet_error: "There was an error adding pass to your wallet. Please try later.",
        insurance_card_no_card_no_share: "Share is unavailable unless the ID card images have been successfully downloaded.",
        messages_caught_up: "You’re all caught up!",
        messages_from: "From: ",
        messages_new: "New",
        messages_no_new: "You have no new messages.",
        messages_see_all: "See All",
        messages_title: "MESSAGES",
        notifications_text: "Text",
        notifications_text_description: "Notifications will be sent to this number: ",
        notifications_email: "Email",
        notifications_email_description: "Notifications will be sent to this email: ",
        notifications_push: "Push",
        notifications_push_description: "Push notification changes made will apply to this device only",
        pharmacy_account_setup_account_linked: "Account linked, please re-login.",
        pharmacy_account_setup_button: "Link Account",
        pharmacy_account_setup_link_error: "There was an issue linking your pharmacy account. Please log out and log back in again. If that fails, contact the help desk.",
        pharmacy_account_setup_unknown_error: "There was an issue linking your pharmacy account. Please check your connection and try again or contact the help desk for support.",
        pharmacy_account_setup_call_pharmacy_error: "There was a mismatch with the information submitted. Please try again or contact your pharmacy to further assist you.",
        pharmacy_account_setup_dob_placeholder: "Enter Date of Birth",
        pharmacy_account_setup_header: "Use the form below to quickly set up your account.",
        pharmacy_account_setup_rx_number_placeholder: "Enter RX Number",
        pharmacy_account_setup_title: "Link Your Pharmacy Information",
        pharmacy_already_prescriptions: "Already have prescriptions with a BSW pharmacy? Link your account!",
        pharmacy_did_you_know: "Did you know that we have a pharmacy location just {0} miles away from you?",
        pharmacy_easily_transfer: "Easily transfer your prescriptions from a Non-BSW Pharmacy (e.g. CVS, Kroger) to a BSW Pharmacy.",
        pharmacy_get_started: "Get Started",
        pharmacy_link_your_account: "Link your account",
        pharmacy_set_up_your_account: "Set up your account",
        pharmacy_notifications_error_saving_prefs: "There was an error saving your preferences.",
        pharmacy_new_request: "New Request",
        pharmacy_dismiss_request: "Dismiss Request",
        pharmacy_transfer_in_progress: "Transfer in Progress",
        prescription_bswh_header: "BSW PHARMACY",
        prescription_bswh_pharmacy: "BSW Pharmacy",
        prescription_ready_for_pickup: "Prescriptions Ready for Pickup",
        prescription_ready_for_refill: "Prescriptions to Refill",
        prescription_manage_dependant: "Manage your dependant’s prescriptions.",
        prescription: "Prescription",
        registration_title: "Registration",
        registration_duplicate_errpr: "This account has already been registered.",
        registration_other_error: "There was an error processing this registration.  Please try again later or contact the help desk.",
        registration_cant_connect: "Unable to load the registration website. Please check your connection and try again.",
        terms_and_conditions_button_title: "I Accept",
        terms_and_conditions_error: "Error saving acceptance status.",
        test_results_header: "TEST RESULTS",
        evisit_title: "Skip the doctor’s office with an E-Visit",
        evisit_online_Interview: "Online Interview",
        evisit_Diagnosis: "Diagnosis by a Clinician",
        evisit_response_prescription: "Response & Prescription (if needed) in 1hr",
        evisit_cant_connect: "Unable to load the E-Visit website. Please check your connection and try again.",
        evisit_eligibility_check_error: "We were unable to verify your eligibility for an eVisit. Please check your connection and try again.",
        evisit_ineligibility_message: "You are currently not eligible to complete an E-Visit. Patients between the ages of 2 and 65 must have seen a BSWH provider in person within the past 12 months to be eligible. Please contact your clinic or use MyBSWHealth to schedule an appointment.",
        evisit_find_a_doctor_button_title: "Find a Doctor",
        start_evisit: "Start E-Visit",
        sympotms_title: "symptoms we treat",
        symptopm_cold_flu_allergies: "Cold, Flu, Allergies",
        symptopm_skin_conditions: "Skin Conditions",
        symptopm_tobacco_cessation: "Tobacco Cessation",
        symptopm_stomach_and_digestive_issues: "Stomach and Digestive Issues",
        symptopm_minor_eye_conditions: "Minor Eye Conditions",
        symptopm_vaginal_yeast_infection: "Vaginal yeast infection",
        symptopm_bladder_infection: "Bladder infection (UTI)",
        evisit_footer_title: "Don’t see an option that works for you? Set up an office visit with a doctor.",
        find_a_doctor: "Find a doctor",
        welcome_text: "Welcome to MyBSWHealth",
        thrive_wellness_title: "Thrive Health Screening",
        thrive_wellness_button_title: "Get Started",
        thrive_wellness_baylor: "Baylor Scott & White Employees, it's that time again.",
        thrive_wellness_submit: "Submit your Thrive health screening by ",
        thrive_wellness_date: "November 9 ",
        thrives_wellness_pay_periods: "in order to avoid paying an additional $30 per pay period in 2019. To complete the Thrive Health Screening, you must be a Baylor Scott & White Employee. Spouses are optional and may submit only if desired.",
        thrive_wellness_complete: "To complete the Thrive Health Screening you must be a BSW employee or spouse.",
        transfer: "Transfer: ",
        error_message_address1: "Please enter valid address line 1",
        error_message_phone: "Please enter valid phone number",
        error_message_email: "Please enter valid email address",
        error_message_city: "Please enter valid city",
        error_message_state: "Please enter valid state",
        error_message_zip_code: "Please enter valid zip code",
        error_message_company_name: "Please enter valid company name",
        error_message_member_id: "Please enter valid member ID",
        error_message_group_id: "Please enter valid group ID",


    }
});